server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/foodXpert
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
SPRING.JPA.HIBERNATE.DDL-AUTO=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

aws.accessKeyId=45ubhp827np6chub7e38fumplt
aws.secretKey=us-east-2_dcVYR5SSi
